[build]
builder = "nixpacks"
buildCommand = "cd /app && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 